apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-app
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/bbharat3/helm.git
    targetRevision: HEAD
    path: my-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp                                 # optional required with default namespace
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true