apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler

metadata:
  name: {{ .Values.hpa.pod }}
  labels:
    nodeType: {{ .Values.deployment.nodeType }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # apiVersion: argoproj.io/v1alpha1
    # kind: Rollout
    name: {{ .Values.deployment.name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  # targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 50
  metrics:
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 50
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50

  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 30 
