apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: {{ .Values.hpa.pod }}
  labels:
    nodeType: {{ .Values.deployment.nodeType }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deployment.name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  # - type: Resource
  #   resource:
  #     name: memory
  #     targetAverageUtilization: 50

        # - type: Resource
        #   resource:
        #     name: cpu
        #     target:
        #       type: Utilization
        #       averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
